spring.application.name=Book-My-Show
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/BookMyShowDataBase
spring.datasource.username=postgres
spring.datasource.password=Mvinod@4284
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
